// Order form
// General
export const SET_NAME = "SET_NAME";
export const SAVE_RUNON_PLATFORMS = "SAVE_RUNON_PLATFORMS";
export const SAVE_MARKETING_GOAL = "SAVE_MARKETING_GOAL";

// Audience
export const SAVE_LOCATION = "SAVE_LOCATION";
export const SAVE_AGE_FROM = "SAVE_AGE_FROM";
export const SAVE_AGE_TO = "SAVE_AGE_TO";
export const SAVE_INTERESTS = "SAVE_INTERESTS";

// Placements
export const SAVE_DEVICES = "SAVE_DEVICES";
export const SAVE_URL = "SAVE_URL"
export const SAVE_PIC_OR_VIDEO = "SAVE_PIC_OR_VIDEO"
export const SAVE_BUTTON_LABEL = "SAVE_BUTTON_LABEL"
export const SAVE_FACEBOOK_PLACEMENTS = "SAVE_FACEBOOK_PLACEMENTS";
export const SAVE_FACEBOOK_AD_DETAILS = "SAVE_FACEBOOK_AD_DETAILS";
export const SAVE_GOOGLE_DETAILS = "SAVE_GOOGLE_DETAILS";

// Budget and schdule
export const SAVE_BUDGET_AND_SCHEDULE = "SAVE_BUDGET_AND_SCHEDULE"

